import os

ENV = os.getenv("FLASK_ENV")
DEBUG = ENV == "development"

SECRET_KEY = os.getenv("SECRET_KEY")
SQLALCHEMY_DATABASE_URI = os.getenv("SQLALCHEMY_DATABASE_URI")
SQLALCHEMY_TRACK_MODIFICATIONS = 'True' == os.getenv("SQLALCHEMY_TRACK_MODIFICATIONS")

JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
JWT_TOKEN_LOCATION = os.getenv("JWT_TOKEN_LOCATION")
JWT_COOKIE_SECURE = ENV != "development"
JWT_ACCESS_TOKEN_EXPIRES = int(os.getenv("JWT_ACCESS_TOKEN_EXPIRES")) 
JWT_COOKIE_CSRF_PROTECT = 'True' == os.getenv("JWT_COOKIE_CSRF_PROTECT")
JWT_CSRF_IN_COOKIES = 'True' == os.getenv("JWT_CSRF_IN_COOKIES")
JWT_COOKIE_SAMESITE = os.getenv("JWT_COOKIE_SAMESITE")
JWT_CSRF_METHODS = (os.getenv("JWT_CSRF_METHODS")).split()
