"""map -> filename, map_name now unique

Revision ID: 08c7351f3ca6
Revises: 7bcec9358414
Create Date: 2021-12-21 18:15:10.609155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c7351f3ca6'
down_revision = '7bcec9358414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'map', ['filename'])
    op.create_unique_constraint(None, 'map', ['map_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'map', type_='unique')
    op.drop_constraint(None, 'map', type_='unique')
    # ### end Alembic commands ###
