"""added team and team_player tables

Revision ID: 68c50058879f
Revises: 96a0d935f7ef
Create Date: 2021-12-23 19:08:28.068175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c50058879f'
down_revision = '96a0d935f7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('games_won', sa.Integer(), nullable=False),
    sa.Column('games_lost', sa.Integer(), nullable=False),
    sa.Column('games_tied', sa.Integer(), nullable=False),
    sa.Column('rounds_won', sa.Integer(), nullable=False),
    sa.Column('rounds_lost', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_team',
    sa.Column('match_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('start_side', sa.String(length=2), nullable=False),
    sa.Column('captain_id', sa.Integer(), nullable=True),
    sa.Column('rounds_won', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['captain_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'team_id')
    )
    op.create_table('team_player',
    sa.Column('team_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('kills', sa.SmallInteger(), nullable=False),
    sa.Column('assists', sa.SmallInteger(), nullable=False),
    sa.Column('deaths', sa.SmallInteger(), nullable=False),
    sa.Column('adr', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['group_player.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'player_id')
    )
    op.create_table('match_player',
    sa.Column('match_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('steam_username', sa.String(length=32), nullable=False),
    sa.Column('steam_avatar_hash', sa.String(length=64), nullable=False),
    sa.Column('kills', sa.SmallInteger(), nullable=False),
    sa.Column('assists', sa.SmallInteger(), nullable=False),
    sa.Column('deaths', sa.SmallInteger(), nullable=False),
    sa.Column('adr', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['match_id', 'team_id'], ['match_team.match_id', 'match_team.team_id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['group_player.player_id'], ),
    sa.ForeignKeyConstraint(['team_id', 'player_id'], ['team_player.team_id', 'team_player.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'player_id')
    )
    op.add_column('group_player', sa.Column('kills', sa.SmallInteger(), nullable=False))
    op.add_column('group_player', sa.Column('assists', sa.SmallInteger(), nullable=False))
    op.add_column('group_player', sa.Column('deaths', sa.SmallInteger(), nullable=False))
    op.add_column('group_player', sa.Column('adr', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_player', 'adr')
    op.drop_column('group_player', 'deaths')
    op.drop_column('group_player', 'assists')
    op.drop_column('group_player', 'kills')
    op.drop_table('match_player')
    op.drop_table('team_player')
    op.drop_table('match_team')
    op.drop_table('team')
    # ### end Alembic commands ###
