"""added map and match table

Revision ID: 6bb11c811b4e
Revises: f455b91cf53b
Create Date: 2021-12-21 14:29:47.291074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb11c811b4e'
down_revision = 'f455b91cf53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=32), nullable=True),
    sa.Column('map_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('date_played', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['map.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_date_played'), 'match', ['date_played'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_date_played'), table_name='match')
    op.drop_table('match')
    op.drop_table('map')
    # ### end Alembic commands ###
