"""map -> added is_active_duty column

Revision ID: 7bcec9358414
Revises: 6bb11c811b4e
Create Date: 2021-12-21 14:36:22.273398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bcec9358414'
down_revision = '6bb11c811b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map', sa.Column('is_active_duty', sa.Boolean(), nullable=False))
    op.alter_column('map', 'filename',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('map', 'map_name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('map', 'map_name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('map', 'filename',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.drop_column('map', 'is_active_duty')
    # ### end Alembic commands ###
