"""added group, group_player tables

Revision ID: 96a0d935f7ef
Revises: 08c7351f3ca6
Create Date: 2021-12-23 15:49:25.504942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a0d935f7ef'
down_revision = '08c7351f3ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_player',
    sa.Column('group_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('group_username', sa.String(length=32), nullable=True),
    sa.Column('group_clearance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'player_id'),
    sa.UniqueConstraint('group_username')
    )
    op.add_column('match', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'match', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_column('match', 'group_id')
    op.drop_table('group_player')
    op.drop_table('group')
    # ### end Alembic commands ###
