"""MatchPlayer, team_id nullable to false

Revision ID: c7cdd22c9732
Revises: 68c50058879f
Create Date: 2021-12-24 00:21:00.955626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7cdd22c9732'
down_revision = '68c50058879f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_player', 'team_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_player', 'team_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
