"""empty message

Revision ID: d9c342d3b8c9
Revises: eb3c64dc954a
Create Date: 2022-08-24 19:22:10.855112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c342d3b8c9'
down_revision = 'eb3c64dc954a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('username', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'username')
    # ### end Alembic commands ###
