"""empty message

Revision ID: eb3c64dc954a
Revises: 
Create Date: 2022-08-23 20:41:32.200383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb3c64dc954a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map', sa.Column('is_removed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map', 'is_removed')
    # ### end Alembic commands ###
