"""initial migration

Revision ID: 0e9142485b6c
Revises: 
Create Date: 2021-07-17 16:29:11.044829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e9142485b6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    None
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    None
    # ### end Alembic commands ###
