"""empty message

Revision ID: 54db04a73d6b
Revises: a3a072c9d84e
Create Date: 2021-07-19 18:08:55.250342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54db04a73d6b'
down_revision = 'a3a072c9d84e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('profile_pic_url', sa.Text(), nullable=False))
    op.alter_column('player', 'preferred_username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'preferred_username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.drop_column('player', 'profile_pic_url')
    # ### end Alembic commands ###
