"""empty message

Revision ID: 8d3df6bc47dd
Revises: 0ec772c747bb
Create Date: 2021-08-11 13:28:28.576022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d3df6bc47dd'
down_revision = '0ec772c747bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    op.add_column('player', sa.Column('acct_type', sa.String(length=16), nullable=False))
    op.add_column('player', sa.Column('permission_clearance', sa.SmallInteger(), nullable=True))
    op.drop_column('player', 'is_admin')
    op.drop_column('player', 'clearance')
    op.drop_column('player', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('player', sa.Column('clearance', mysql.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('is_admin', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.drop_column('player', 'permission_clearance')
    op.drop_column('player', 'acct_type')
    op.create_table('admin',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clearance', mysql.SMALLINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['player.id'], name='admin_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
