"""match changes

Revision ID: a3a072c9d84e
Revises: 0e9142485b6c
Create Date: 2021-07-17 16:41:53.228026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3a072c9d84e'
down_revision = '0e9142485b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('map_name', table_name='map')
    op.add_column('match', sa.Column('map_id', sa.Integer(), nullable=False))
    op.drop_constraint('match_ibfk_1', 'match', type_='foreignkey')
    op.create_foreign_key(None, 'match', 'map', ['map_id'], ['id'])
    op.drop_column('match', 'map_filename')
    op.drop_index('filename', table_name='map')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('map_filename', mysql.VARCHAR(length=32), nullable=False))
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.create_foreign_key('match_ibfk_1', 'match', 'map', ['map_filename'], ['filename'])
    op.drop_column('match', 'map_id')
    op.create_index('map_name', 'map', ['map_name'], unique=False)
    op.create_index('filename', 'map', ['filename'], unique=False)
    # ### end Alembic commands ###
